name: Update Velog Posts

on:
  schedule:
    # 매일 00:00 UTC 실행 → 한국시간(Asia/Seoul) 기준 매일 09:00
    - cron: '0 0 * * *'
  workflow_dispatch: # 필요 시 수동 실행 버튼

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with Velog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://v2.velog.io/rss/@nas7062"
          # max_post_count: "5"        # 표시할 글 개수(기본 5개)
          # template: "$title - $url"  # 한 줄 템플릿
